// <auto-generated />
using System;
using EF_CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(Student_DbContext))]
    partial class Student_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("GradeId")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Math",
                            Section = "ASP",
                            StudentID = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Biology",
                            Section = "ASP",
                            StudentID = 1
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "Geography ",
                            Section = "ASP",
                            StudentID = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "Computer Science",
                            Section = "ASP",
                            StudentID = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Physics",
                            Section = "ASP",
                            StudentID = 2
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "English",
                            Section = "ASP",
                            StudentID = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "History",
                            Section = "ASP",
                            StudentID = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StudentID");

                    b.HasIndex("StudentName", "StudentID")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(2002, 10, 15, 19, 32, 22, 880, DateTimeKind.Local).AddTicks(3251),
                            Height = 185m,
                            StudentName = "Antonijo Tomic",
                            Weight = 90m
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(1989, 10, 15, 19, 32, 22, 880, DateTimeKind.Local).AddTicks(3316),
                            Height = 190m,
                            StudentName = "Ratko Cosic",
                            Weight = 90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
